### ISSUE TITLE
User's own messages are not backfilled without login-matrix

### ISSUE THREAD

**Issue by lukaslihotzki** [tulir/mautrix-hangouts#29]
After Google login, mautrix-hangouts created Matrix rooms (without messages). After mautrix-hangouts restart, it started to backfill messages, except my own, although the puppet of my Google account joined (and left after backfill).

The solution was login-matrix. This allowed the puppet of my Google account to join again, backfill my own messages, and leave. However, only the messages I sent after every other person were synced because of this "`Stopping backfilling at `[...]` as message was already bridged`"-check. `invite_own_puppet: true` was set all the time, so these messages were sent using the puppet instead of my Matrix account, so login-matrix should not even be needed.

Full backfill config:
```
    backfill:
        invite_own_puppet: true
        initial_limit: 0
        missed_limit: 100
        disable_notifications: false
```
